CREATE TABLE PRODUCTS (
    ID RAW(16) NOT NULL,
    NAME VARCHAR(120) NOT NULL,
    CATEGORY VARCHAR(255) NOT NULL,
    UNIT_PRICE DECIMAL(38,2) NOT NULL,
    EXPIRATION_DATE DATE,
    STOCK_QUANTITY INT NOT NULL,
    CREATION_DATE TIMESTAMP,
    UPDATE_DATE TIMESTAMP,
    PRIMARY KEY (ID)
);